# Start message for /start command
START_MESSAGE: "Hey Carlos, I'm your assistant bot. I can help you with your daily tasks."

# Timeouts times in seconds
TIMEOUT: 30

# Path for the error log file
ERROR_LOG_FILE: "assistantbot/logs/assistantbot_error.log"