name: Build and Deploy to Azure Container Registry

on:
  workflow_run:
    workflows: ["Code Quality"]
    branches: [main]
    types:
      - completed

  workflow_dispatch: 
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure
        run: |
          az login

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ env.IMAGE_NAME }} .

      - name: Log in to Container Registry
        run: |
          az acr login --name ${{ env.CONTAINER_REGISTRY }}

      - name: Tag Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to Container Registry
        run: |
          docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest