name: Deploy image on Azure Container Registry
on:
  push:
    branches:
      - develop

env:
  CONTAINER_REGISTRY: assistantbotcontainer
  IMAGE_NAME: assistantbot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t ${{ env.IMAGE_NAME }} .

      - name: Log in to Azure
        run: az login --u ${{ secrets.AZURE_USERNAME }} --p ${{ secrets.AZURE_PASSWORD }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.CONTAINER_REGISTRY }}

      - name: Tag Docker image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to Azure Container Registry
        run: docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
