name: Deploy to VM

on:
  workflow_run:
    workflows: ["Build and Deploy to Azure Container Registry"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
        with:
          envs: IMAGE_NAME, CONTAINER_REGISTRY
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Get the IDs of all running containers
            container_ids=$(docker ps -q)

            # Check if there are any running containers
            if [[ -n "$container_ids" ]]; then
              # Kill the running containers
              docker kill $container_ids
            fi

            az acr login --name $CONTAINER_REGISTRY
            docker pull $CONTAINER_REGISTRY.azurecr.io/$IMAGE_NAME:latest
            docker run -d --restart unless-stopped --env-file personal-assistant/.env $CONTAINER_REGISTRY.azurecr.io/$IMAGE_NAME:latest
